[workspace]
resolver = "2"
members = [
    "sdif-sys",
    "sdif-rs",
    "mat2sdif",
]

[workspace.package]
version = "0.3.3"
edition = "2021"
license = "MIT"
repository = "https://github.com/oxur/sdif"
rust-version = "1.70"
